columns:
  - id: int  
  - diagnosis: object 
  - radius_mean: float64
  - texture_mean: float64
  - perimeter_mean: float64
  - area_mean: float64
  - smoothness_mean: float64
  - compactness_mean: float64
  - concavity_mean: float64
  - concave points_mean: float64
  - symmetry_mean: float64
  - fractal_dimension_mean: float64
  - radius_se: float64
  - texture_se: float64
  - perimeter_se: float64
  - area_se: float64
  - smoothness_se: float64
  - compactness_se: float64
  - concavity_se: float64
  - concave points_se: float64
  - symmetry_se: float64
  - fractal_dimension_se: float64
  - radius_worst: float64
  - texture_worst: float64
  - perimeter_worst: float64
  - area_worst: float64
  - smoothness_worst: float64
  - compactness_worst: float64
  - concavity_worst: float64
  - concave points_worst: float64
  - symmetry_worst: float64
  - fractal_dimension_worst: float64
  - Unnamed 32: float64

numerical_columns:
  - id
  - radius_mean
  - texture_mean
  - perimeter_mean
  - area_mean
  - smoothness_mean
  - compactness_mean
  - concavity_mean
  - concave points_mean
  - symmetry_mean
  - fractal_dimension_mean
  - radius_se
  - texture_se
  - perimeter_se
  - area_se
  - smoothness_se
  - compactness_se
  - concavity_se
  - concave points_se
  - symmetry_se
  - fractal_dimension_se
  - radius_worst
  - texture_worst
  - perimeter_worst
  - area_worst
  - smoothness_worst
  - compactness_worst
  - concavity_worst
  - concave points_worst
  - symmetry_worst
  - fractal_dimension_worst
  - Unnamed 32

categorical_columns:
  - diagnosis

drop_columns:
  - id
  - Unnamed 32
